"""Compatibility shim - the bot now lives in the `sigma` package. Run `python bot.py`.
This module re-exports every name so existing tools (tests, bot_selfcheck.py) keep working."""
import importlib as _il
_m = _il.import_module('sigma.logging_setup'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.config'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.core'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.ops'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.http'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.storage'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.market_data'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.charts_theme'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.calculations'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.members'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.cards'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.sizer'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.boards'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.tracker'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.news'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.telegram'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.alerts'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.liquidations'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.xfeed'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.jobs'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.results'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.recaps'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.commands_trades'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.commands_terminal'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.commands_help'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.errors'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.services.store'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.services.trades'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.commands_setup'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.commands_admin'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.aliases'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.health'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
_m = _il.import_module('sigma.app'); globals().update({k: v for k, v in vars(_m).items() if not k.startswith('__')})
if __name__ == '__main__':
    from sigma.core import bot
    from sigma.config import BOT_TOKEN
    if not BOT_TOKEN or BOT_TOKEN == "PASTE_TOKEN_HERE":
        raise SystemExit("SCIENT_BOT_TOKEN is not set - refusing to start.")
    bot.run(BOT_TOKEN, log_handler=None)
